from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


TaskType = Literal["rag_qa", "summary", "semantic_explain", "tool_call", "text_to_video"]
Priority = Literal["normal", "high"]
BackendType = Literal["mock", "rag", "ollama", "agent"]
GatewayStatus = Literal["success", "failed", "timeout", "fallback_success", "rate_limited"]
AgenticTaskType = Literal[
    "knowledge_qa",
    "doc_review",
    "incident_analysis",
    "media_generation",
    "tool_task",
    "chat",
]
AgenticStatus = Literal["success", "refused", "fallback_success", "failed", "rate_limited"]
RiskLevel = Literal["low", "medium", "high"]
CostBudget = Literal["low", "normal", "high"]
CostLevel = Literal["low", "normal", "high"]
WorkflowType = Literal["langgraph", "stub"]
IntentMode = Literal["rule_based", "llm_intent_placeholder"]
ResourceBalanceStrategy = Literal["match_first_resource_tiebreak"]
TraceEventType = Literal[
    "profile_build",
    "route_decision",
    "node_start",
    "node_end",
    "tool_call",
    "rag_retrieve",
    "model_call",
    "error",
    "fallback",
]
TraceEventStatus = Literal["success", "failed", "skipped", "permission_denied", "timeout"]


class GatewayRequest(BaseModel):
    request_id: Optional[str] = Field(default=None, description="Client supplied id; generated by gateway when missing.")
    user_id: str = Field(min_length=1)
    tenant_id: str = Field(default="tenant_basic", min_length=1)
    task_type: TaskType
    input: str = Field(min_length=1)
    priority: Priority = "normal"
    stream: bool = False
    metadata: Dict[str, Any] = Field(default_factory=dict)


class BackendInfo(BaseModel):
    backend_id: str
    backend_type: BackendType
    url: str
    supported_tasks: List[TaskType]
    supports_streaming: bool = False
    healthy: bool = True


class BackendResponse(BaseModel):
    request_id: str
    backend_id: str
    task_type: TaskType
    output: str
    heuristic_quality_score: float = Field(ge=0.0, le=1.0)
    latency_ms: float = Field(ge=0.0)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class GatewayResponse(BaseModel):
    request_id: str
    status: GatewayStatus
    selected_backend: Optional[str]
    output: Optional[str] = None
    heuristic_quality_score: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    latency_ms: float
    fallback_backend: Optional[str] = None
    fallback_reason: Optional[str] = None
    error: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class RequestLog(BaseModel):
    request_id: str
    user_id: str
    tenant_id: str
    task_type: TaskType
    policy: str
    selected_backend: Optional[str]
    latency_ms: float
    status: GatewayStatus
    retry_count: int = 0
    fallback_backend: Optional[str] = None
    fallback_reason: Optional[str] = None
    error: Optional[str] = None
    candidate_backends: List[str] = Field(default_factory=list)
    attempts: List[Dict[str, Any]] = Field(default_factory=list)
    rate_limit: Dict[str, Any] = Field(default_factory=dict)
    routing: Dict[str, Any] = Field(default_factory=dict)
    circuit_breakers: Dict[str, Any] = Field(default_factory=dict)
    fallback_used: bool = False
    timestamp: str


class ServiceProfile(BaseModel):
    backend_id: str
    task_type: TaskType
    heuristic_quality_score: float = Field(ge=0.0, le=1.0)
    avg_latency_ms: float = Field(ge=0.0)
    p95_latency_ms: float = Field(ge=0.0)
    error_rate: float = Field(ge=0.0, le=1.0)
    timeout_rate: float = Field(ge=0.0, le=1.0)
    last_updated: str


class AgenticGatewayRequest(BaseModel):
    request_id: Optional[str] = Field(default=None, description="Client supplied id; generated by gateway when missing.")
    user_id: str = Field(min_length=1)
    tenant_id: str = Field(default="tenant_demo", min_length=1)
    task_type: AgenticTaskType
    input: str = Field(min_length=1)
    priority: Priority = "normal"
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AuthenticatedConsumer(BaseModel):
    consumer_id: str
    api_key_id: str
    permissions: List[str] = Field(default_factory=list)
    allowed_workflows: List[str] = Field(default_factory=list)
    allowed_tools: List[str] = Field(default_factory=list)
    rate_limit_key: str
    auth_latency_ms: float = Field(default=0.0, ge=0.0)


class Citation(BaseModel):
    source_id: str
    title: str
    chunk_id: str
    score: float = Field(ge=0.0)


class AgenticMetrics(BaseModel):
    latency_ms: float = Field(ge=0.0)
    estimated_tokens: int = Field(default=0, ge=0)
    estimated_cost: float = Field(default=0.0, ge=0.0)


class AgenticGatewayResponse(BaseModel):
    request_id: str
    trace_id: str
    selected_workflow: Optional[str]
    selection_reason: str
    answer: Optional[str] = None
    citations: List[Citation] = Field(default_factory=list)
    status: AgenticStatus
    metrics: AgenticMetrics
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TaskProfile(BaseModel):
    task_type: AgenticTaskType
    required_capabilities: List[str] = Field(default_factory=list)
    required_tools: List[str] = Field(default_factory=list)
    evidence_required: bool = False
    risk_level: RiskLevel = "low"
    latency_slo_ms: float = Field(default=5000.0, gt=0.0)
    cost_budget: CostBudget = "normal"
    permission_scope: List[str] = Field(default_factory=list)
    priority: Priority = "normal"
    task_type_hint: Optional[AgenticTaskType] = None
    profile_reason: List[str] = Field(default_factory=list)


class WorkflowProfile(BaseModel):
    workflow_id: str
    workflow_type: WorkflowType = "stub"
    supported_tasks: List[AgenticTaskType]
    capabilities: List[str]
    allowed_tools: List[str] = Field(default_factory=list)
    required_permission_scope: List[str] = Field(default_factory=list)
    avg_latency_ms: float = Field(ge=0.0)
    p95_latency_ms: float = Field(ge=0.0)
    success_rate: float = Field(ge=0.0, le=1.0)
    citation_coverage: float = Field(ge=0.0, le=1.0)
    tool_success_rate: float = Field(ge=0.0, le=1.0)
    error_rate: float = Field(ge=0.0, le=1.0)
    cost_level: CostLevel = "normal"
    healthy: bool = True
    metrics_source: Literal["seed", "eval"] = "seed"
    updated_by_eval_run_id: Optional[str] = None
    metrics_report_path: Optional[str] = None


class CandidateWorkflowScore(BaseModel):
    workflow_id: str
    score: float = Field(ge=0.0)
    match_score: float = Field(default=0.0, ge=0.0, le=1.0)
    resource_score: float = Field(default=0.0, ge=0.0, le=1.0)
    executable: bool
    exclusion_reason: Optional[str] = None
    selection_reason: str
    capability_match: float = Field(ge=0.0, le=1.0)
    tool_match: float = Field(ge=0.0, le=1.0)
    permission_match: float = Field(ge=0.0, le=1.0)
    consumer_workflow_access: float = Field(default=1.0, ge=0.0, le=1.0)
    consumer_tool_access: float = Field(default=1.0, ge=0.0, le=1.0)
    historical_success: float = Field(ge=0.0, le=1.0)
    citation_coverage: float = Field(ge=0.0, le=1.0)
    latency_score: float = Field(ge=0.0, le=1.0)
    cost_score: float = Field(ge=0.0, le=1.0)
    risk_fit: float = Field(ge=0.0, le=1.0)


class AgenticIntentDecision(BaseModel):
    mode: IntentMode
    task_type_hint: Optional[AgenticTaskType]
    inferred_task_type: AgenticTaskType
    matched_reasons: List[str] = Field(default_factory=list)
    llm_intent_enabled: bool = False


class ResourceCandidateScore(BaseModel):
    target_id: str
    workflow_id: str
    match_score: float = Field(ge=0.0, le=1.0)
    resource_score: float = Field(ge=0.0, le=1.0)
    avg_latency_ms: float = Field(ge=0.0)
    p95_latency_ms: float = Field(ge=0.0)
    error_rate: float = Field(ge=0.0, le=1.0)
    cost_level: CostLevel
    runtime_load_score: float = Field(default=1.0, ge=0.0, le=1.0)
    ongoing_count: int = Field(default=0, ge=0)
    recent_sample_count: int = Field(default=0, ge=0)
    recent_avg_latency_ms: Optional[float] = Field(default=None, ge=0.0)
    recent_p95_latency_ms: Optional[float] = Field(default=None, ge=0.0)
    recent_error_rate: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    metrics_source: str


class AgenticResourceDecision(BaseModel):
    strategy: ResourceBalanceStrategy
    selected_target: Optional[str]
    selected_workflow: Optional[str]
    selection_reason: str
    candidate_targets: List[ResourceCandidateScore] = Field(default_factory=list)
    tie_threshold: float = Field(default=0.05, ge=0.0, le=1.0)


class AgenticRouteDecision(BaseModel):
    trace_id: str
    selected_workflow: Optional[str]
    candidate_scores: List[CandidateWorkflowScore]
    excluded_candidates: List[Dict[str, Any]] = Field(default_factory=list)
    selection_reason: str
    score_breakdown: Dict[str, Any]
    intent_decision: AgenticIntentDecision
    resource_decision: AgenticResourceDecision


class TraceEvent(BaseModel):
    trace_id: str
    request_id: str
    event_id: str
    service: str
    node: str
    event_type: TraceEventType
    input_summary: str = ""
    output_summary: str = ""
    status: TraceEventStatus = "success"
    latency_ms: float = Field(default=0.0, ge=0.0)
    estimated_tokens: int = Field(default=0, ge=0)
    estimated_cost: float = Field(default=0.0, ge=0.0)
    error_type: Optional[str] = None
    timestamp: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentInvocationRequest(BaseModel):
    request_id: str
    trace_id: str
    consumer_id: str = "unknown_consumer"
    user_id: str
    tenant_id: str
    input: str
    selected_workflow: str
    task_profile: TaskProfile
    permissions: List[str] = Field(default_factory=list)
    allowed_tools: List[str] = Field(default_factory=list)
    allowed_workflows: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentWorkflowResponse(BaseModel):
    request_id: str
    trace_id: str
    selected_workflow: str
    answer: str
    citations: List[Citation] = Field(default_factory=list)
    status: AgenticStatus
    metrics: AgenticMetrics
    tools: List[str] = Field(default_factory=list)
    trace_events: List[TraceEvent] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
