from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


Priority = Literal["normal", "high"]
AgenticTaskType = Literal[
    "knowledge_qa",
    "coding",
    "media_generation",
    "document_writing",
]
AgenticStatus = Literal["success", "refused", "fallback_success", "failed", "rate_limited", "verification_failed"]
RiskLevel = Literal["low", "medium", "high"]
CostBudget = Literal["low", "normal", "high"]
CostLevel = Literal["low", "normal", "high"]
WorkflowType = Literal["langgraph", "stub"]
IntentMode = Literal["rule_based", "llm_intent_placeholder"]
ResourceBalanceStrategy = Literal["match_first_resource_tiebreak"]
PreviewStatus = Literal["ready", "warning", "blocked"]
CriterionType = Literal[
    "trace_event_required",
    "tool_success_required",
    "citation_required",
    "citation_source_required",
    "schema_field_required",
    "resource_forbidden",
    "metadata_required",
]
CriterionStatus = Literal["passed", "failed", "skipped"]
TraceEventType = Literal[
    "profile_build",
    "route_decision",
    "node_start",
    "node_end",
    "tool_call",
    "rag_retrieve",
    "model_call",
    "error",
    "fallback",
]
TraceEventStatus = Literal["success", "failed", "skipped", "permission_denied", "timeout"]


class AgenticGatewayRequest(BaseModel):
    request_id: Optional[str] = Field(default=None, description="Client supplied id; generated by gateway when missing.")
    user_id: str = Field(min_length=1)
    tenant_id: str = Field(default="tenant_demo", min_length=1)
    task_type: AgenticTaskType
    input: str = Field(min_length=1)
    priority: Priority = "normal"
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AuthenticatedConsumer(BaseModel):
    consumer_id: str
    api_key_id: str
    permissions: List[str] = Field(default_factory=list)
    allowed_workflows: List[str] = Field(default_factory=list)
    allowed_tools: List[str] = Field(default_factory=list)
    rate_limit_key: str
    auth_latency_ms: float = Field(default=0.0, ge=0.0)


class Citation(BaseModel):
    source_id: str
    title: str
    chunk_id: str
    score: float = Field(ge=0.0)


class AgenticMetrics(BaseModel):
    latency_ms: float = Field(ge=0.0)
    estimated_tokens: int = Field(default=0, ge=0)
    estimated_cost: float = Field(default=0.0, ge=0.0)


class AgenticGatewayResponse(BaseModel):
    request_id: str
    trace_id: str
    contract_id: Optional[str] = None
    selected_workflow: Optional[str]
    selection_reason: str
    answer: Optional[str] = None
    citations: List[Citation] = Field(default_factory=list)
    status: AgenticStatus
    verification: Optional["VerificationResult"] = None
    metrics: AgenticMetrics
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TaskProfile(BaseModel):
    task_type: AgenticTaskType
    required_capabilities: List[str] = Field(default_factory=list)
    required_tools: List[str] = Field(default_factory=list)
    evidence_required: bool = False
    risk_level: RiskLevel = "low"
    latency_slo_ms: float = Field(default=5000.0, gt=0.0)
    cost_budget: CostBudget = "normal"
    permission_scope: List[str] = Field(default_factory=list)
    priority: Priority = "normal"
    task_type_hint: Optional[AgenticTaskType] = None
    profile_reason: List[str] = Field(default_factory=list)


class WorkflowProfile(BaseModel):
    workflow_id: str
    workflow_type: WorkflowType = "stub"
    supported_tasks: List[AgenticTaskType]
    capabilities: List[str]
    allowed_tools: List[str] = Field(default_factory=list)
    required_permission_scope: List[str] = Field(default_factory=list)
    avg_latency_ms: float = Field(ge=0.0)
    p95_latency_ms: float = Field(ge=0.0)
    success_rate: float = Field(ge=0.0, le=1.0)
    citation_coverage: float = Field(ge=0.0, le=1.0)
    tool_success_rate: float = Field(ge=0.0, le=1.0)
    error_rate: float = Field(ge=0.0, le=1.0)
    cost_level: CostLevel = "normal"
    healthy: bool = True
    metrics_source: Literal["seed", "eval"] = "seed"
    updated_by_eval_run_id: Optional[str] = None
    metrics_report_path: Optional[str] = None


class CandidateWorkflowScore(BaseModel):
    workflow_id: str
    score: float = Field(ge=0.0)
    match_score: float = Field(default=0.0, ge=0.0, le=1.0)
    resource_score: float = Field(default=0.0, ge=0.0, le=1.0)
    executable: bool
    exclusion_reason: Optional[str] = None
    selection_reason: str
    capability_match: float = Field(ge=0.0, le=1.0)
    tool_match: float = Field(ge=0.0, le=1.0)
    permission_match: float = Field(ge=0.0, le=1.0)
    consumer_workflow_access: float = Field(default=1.0, ge=0.0, le=1.0)
    consumer_tool_access: float = Field(default=1.0, ge=0.0, le=1.0)
    historical_success: float = Field(ge=0.0, le=1.0)
    citation_coverage: float = Field(ge=0.0, le=1.0)
    latency_score: float = Field(ge=0.0, le=1.0)
    cost_score: float = Field(ge=0.0, le=1.0)
    risk_fit: float = Field(ge=0.0, le=1.0)
    memory_route_boost: float = Field(default=0.0, ge=0.0, le=0.2)


class AgenticIntentDecision(BaseModel):
    mode: IntentMode
    task_type_hint: Optional[AgenticTaskType]
    inferred_task_type: AgenticTaskType
    matched_reasons: List[str] = Field(default_factory=list)
    llm_intent_enabled: bool = False


class ResourceCandidateScore(BaseModel):
    target_id: str
    workflow_id: str
    match_score: float = Field(ge=0.0, le=1.0)
    resource_score: float = Field(ge=0.0, le=1.0)
    avg_latency_ms: float = Field(ge=0.0)
    p95_latency_ms: float = Field(ge=0.0)
    error_rate: float = Field(ge=0.0, le=1.0)
    cost_level: CostLevel
    runtime_load_score: float = Field(default=1.0, ge=0.0, le=1.0)
    ongoing_count: int = Field(default=0, ge=0)
    recent_sample_count: int = Field(default=0, ge=0)
    recent_avg_latency_ms: Optional[float] = Field(default=None, ge=0.0)
    recent_p95_latency_ms: Optional[float] = Field(default=None, ge=0.0)
    recent_error_rate: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    metrics_source: str


class AgenticResourceDecision(BaseModel):
    strategy: ResourceBalanceStrategy
    selected_target: Optional[str]
    selected_workflow: Optional[str]
    selection_reason: str
    candidate_targets: List[ResourceCandidateScore] = Field(default_factory=list)
    tie_threshold: float = Field(default=0.05, ge=0.0, le=1.0)


class AgenticRouteDecision(BaseModel):
    trace_id: str
    selected_workflow: Optional[str]
    candidate_scores: List[CandidateWorkflowScore]
    excluded_candidates: List[Dict[str, Any]] = Field(default_factory=list)
    selection_reason: str
    score_breakdown: Dict[str, Any]
    intent_decision: AgenticIntentDecision
    resource_decision: AgenticResourceDecision


class AcceptanceCriterion(BaseModel):
    criterion_id: str
    type: CriterionType
    target: str
    required: bool = True
    params: Dict[str, Any] = Field(default_factory=dict)
    description: str = ""


class TaskContract(BaseModel):
    contract_id: str
    task_type: AgenticTaskType
    selected_workflow: Optional[str]
    required_capabilities: List[str] = Field(default_factory=list)
    required_tools: List[str] = Field(default_factory=list)
    required_permissions: List[str] = Field(default_factory=list)
    allowed_resources: Dict[str, List[str]] = Field(default_factory=dict)
    forbidden_resources: Dict[str, List[str]] = Field(default_factory=dict)
    output_schema: Dict[str, Any] = Field(default_factory=dict)
    acceptance_criteria: List[AcceptanceCriterion] = Field(default_factory=list)
    latency_slo_ms: float = Field(default=5000.0, gt=0.0)
    cost_budget: CostBudget = "normal"


class CriterionResult(BaseModel):
    criterion_id: str
    type: CriterionType
    target: str
    status: CriterionStatus
    reason: str = ""


class VerificationResult(BaseModel):
    status: Literal["passed", "failed"]
    passed_count: int = Field(ge=0)
    failed_count: int = Field(ge=0)
    criteria_results: List[CriterionResult] = Field(default_factory=list)
    failure_reason: Optional[str] = None


class GatewayPreviewResponse(BaseModel):
    request_id: str
    trace_id: str
    preview_status: PreviewStatus
    selected_workflow: Optional[str]
    task_profile: TaskProfile
    task_contract: TaskContract
    route_decision: AgenticRouteDecision
    required_permissions: List[str] = Field(default_factory=list)
    missing_permissions: List[str] = Field(default_factory=list)
    required_tools: List[str] = Field(default_factory=list)
    acceptance_criteria: List[AcceptanceCriterion] = Field(default_factory=list)
    reasons: List[str] = Field(default_factory=list)
    next_actions: List[str] = Field(default_factory=list)
    memory_planner: Dict[str, Any] = Field(default_factory=dict)


class TraceEvent(BaseModel):
    trace_id: str
    request_id: str
    event_id: str
    service: str
    node: str
    event_type: TraceEventType
    input_summary: str = ""
    output_summary: str = ""
    status: TraceEventStatus = "success"
    latency_ms: float = Field(default=0.0, ge=0.0)
    estimated_tokens: int = Field(default=0, ge=0)
    estimated_cost: float = Field(default=0.0, ge=0.0)
    error_type: Optional[str] = None
    timestamp: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentInvocationRequest(BaseModel):
    request_id: str
    trace_id: str
    consumer_id: str = "unknown_consumer"
    user_id: str
    tenant_id: str
    input: str
    selected_workflow: str
    task_profile: TaskProfile
    task_contract: Optional[TaskContract] = None
    permissions: List[str] = Field(default_factory=list)
    allowed_tools: List[str] = Field(default_factory=list)
    allowed_workflows: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentWorkflowResponse(BaseModel):
    request_id: str
    trace_id: str
    selected_workflow: str
    answer: str
    citations: List[Citation] = Field(default_factory=list)
    status: AgenticStatus
    metrics: AgenticMetrics
    tools: List[str] = Field(default_factory=list)
    trace_events: List[TraceEvent] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
